### ISSUE TITLE
help nginx proxy a server using SAML2 authentication without losing control of the server

### ISSUE THREAD

**Issue by Muten-007** [nginxinc/nginx-saml#24]
Hello ！Such as ，there is a server using SAML2 authentication  and I use the nginx to proxy it.  When I just use the nginx of my version and get the response from IdP ，it will redirect to the destination address(the app's orginal address ) but not my proxied adrress.  It cause the nginx can not get control of the server and trace the server and it then cannot meet my expectation.   I wonder if this module can help nginx to proxy a server using SAML2 authentication and can always get control of the server? 

Look forward to your reply.

**Comment by route443** [comment]
Hello @Muten-007 ,

Based on your question, it seems you are handling SAML authentication on the proxied application side. This solution allows authentication to be handled by NGINX Plus. However, if your issue is with the redirection from the proxied application, I'd recommend ensuring that your app respects the `X-Forwarded-For` headers:

1. Ensure your proxied app correctly handles the `X-Forwarded-For` and `X-Forwarded-Proto` headers so it generates URLs relative to the proxied/nginx address.

2. Ensure your nginx config forwards these headers. Here is an example:
```nginx
location / {
  proxy_pass http://your_app;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
}
```
